#!/bin/bash
read VAR

echo "content-type: text/html"
echo

IFS=$'\n'
IP=$REMOTE_ADDR
REDIRECT=$(echo $VAR | cut -d"=" -f2 | sed "s/%2F/\//g")
MENUA=/var/www/html/pages/admin.html
MENUC=/var/www/html/pages/common.html
LOGIN=/var/www/html/pages/login.html
TYPE=$(grep ";$IP;" users.csv | cut -d";" -f4)
STATE=$(grep ";$IP;" users.csv | cut -d";" -f6)
PART=$(grep ";$IP;" users.csv | cut -d";" -f7)

grep ";$IP;" users.csv> /dev/null

if [[ $? == "0" ]] ; then
	if [[ $STATE == "logged" ]] ; then
		if [[ $TYPE == "admin" ]] ; then
			if [[ $REDIRECT == "/usr/lib/cgi-bin/vequip.cgi" ]] ; then
				echo "<!DOCTYPE html>"
				echo "<html>"
				echo "<head>"
				echo "<link rel='stylesheet' type='text/css' href='../css/index.css'>" 
				echo "<script>"
				echo "function toggleSidebar(){"
				echo "document.getElementById(\"sidebar\").classList.toggle('active');"
				echo "}"
				echo "</script>"
				echo "</head>"
				echo "<body>"
				echo "<div id=\"sidebar\">"
				echo "<div class=\"toggle-btn\" onclick=\"toggleSidebar()\">"
				echo "<span class=\"span\"></span>"
				echo "<span class=\"span\"></span>"
				echo "<span class=\"span\"></span>"
				echo "</div>"
				cat "$MENUA"
				echo "</div>"
				echo "<div id=\"table-menu\">"
				echo "<table>"
				echo "<tr>"
				echo "<th>Nome:</th>"
				echo "<th>Localização:</th>"
				echo "<th>Endereço de IP:</th>"
				echo "</tr>"
				for x in $(cat equips.csv) ; do
					echo "<tr>"
					for y in $(echo $x) ; do
						NAME=$(echo $y | cut -d";" -f1)
						LOCAL=$(echo $y | cut -d";" -f2)
						IP=$(echo $y | cut -d";" -f3)
						echo "<td>$NAME</td>"
						echo "<td>$LOCAL</td>"
						echo "<td>$IP</td>"
					done
					echo "</tr>"
				done
				echo "</table>"
				echo "</div>"
				echo "</body>"
				echo "</html>"
			elif [[ $REDIRECT == "/usr/lib/cgi-bin/vuser.cgi" ]] ; then
				echo "<!DOCTYPE html>"
				echo "<html>"
				echo "<head>"
				echo "<link rel='stylesheet' type='text/css' href='../css/index.css'>" 
				echo "<script>"
				echo "function toggleSidebar(){"
				echo "document.getElementById(\"sidebar\").classList.toggle('active');"
				echo "}"
				echo "</script>"
				echo "</head>"
				echo "<body>"
				echo "<div id=\"sidebar\">"
				echo "<div class=\"toggle-btn\" onclick=\"toggleSidebar()\">"
				echo "<span class=\"span\"></span>"
				echo "<span class=\"span\"></span>"
				echo "<span class=\"span\"></span>"
				echo "</div>"
				cat "$MENUA"
				echo "</div>"
				echo "<div id=\"table-menu\">"
				echo "<table>"
				echo "<tr>"
				echo "<th>Nome de usuário:</th>"
				echo "<th>Endereço de e-mail:</th>"
				echo "</tr>"
				for x in $(cat users.csv) ; do
					echo "<tr>"
					for y in $(echo $x) ; do
						NAME=$(echo $y | cut -d";" -f1)
						EMAIL=$(echo $y | cut -d";" -f3)
						echo "<td>$NAME</td>"
						echo "<td>$EMAIL</td>"
					done
					echo "</tr>"
				done
				echo "</table>"
				echo "</div>"
				echo "</body>"
				echo "</html>"
			elif [[ $REDIRECT == "/usr/lib/cgi-bin/log/equip.cgi" ]] ; then 
				echo "<!DOCTYPE html>"
				echo "<html>"
				echo "<head>"
				echo "<link rel='stylesheet' type='text/css' href='../css/index.css'>" 
				echo "<script>"
				echo "function toggleSidebar(){"
				echo "document.getElementById(\"sidebar\").classList.toggle('active');"
				echo "}"
				echo "</script>"
				echo "</head>"
				echo "<body>"
				echo "<div id=\"sidebar\">"
				echo "<div class=\"toggle-btn\" onclick=\"toggleSidebar()\">"
				echo "<span class=\"span\"></span>"
				echo "<span class=\"span\"></span>"
				echo "<span class=\"span\"></span>"
				echo "</div>"
				cat "$MENUA"
				echo "</div>"
				echo "<div id=\"table-menu\">"
				echo "<table>"
				echo "<tr>"
				echo "<th>Nome:</th>"
				echo "<th>Ação:</th>"
				echo "<th>Data e hora:</th>"
				echo "</tr>"
				for x in $(cat /usr/lib/cgi-bin/log/equip.txt) ; do
					echo "<tr>"
					for y in $(echo $x) ; do
						NAME=$(echo $y | cut -d";" -f1)
						ACT=$(echo $y | cut -d";" -f2)
						DATE=$(echo $y | cut -d";" -f3)
						echo "<td>$NAME</td>"
						echo "<td>$ACT</td>"
						echo "<td>$DATE</td>"
					done
					echo "</tr>"
				done
				echo "</table>"
				echo "</div>"
				echo "</body>"
				echo "</html>"
			elif [[ $REDIRECT == "/usr/lib/cgi-bin/log/user.cgi" ]] ; then 
				echo "<!DOCTYPE html>"
				echo "<html>"
				echo "<head>"
				echo "<link rel='stylesheet' type='text/css' href='../css/index.css'>" 
				echo "<script>"
				echo "function toggleSidebar(){"
				echo "document.getElementById(\"sidebar\").classList.toggle('active');"
				echo "}"
				echo "</script>"
				echo "</head>"
				echo "<body>"
				echo "<div id=\"sidebar\">"
				echo "<div class=\"toggle-btn\" onclick=\"toggleSidebar()\">"
				echo "<span class=\"span\"></span>"
				echo "<span class=\"span\"></span>"
				echo "<span class=\"span\"></span>"
				echo "</div>"
				cat "$MENUA"
				echo "</div>"
				echo "<div id=\"table-menu\">"
				echo "<table>"
				echo "<tr>"
				echo "<th>Nome de usuário:</th>"
				echo "<th>Ação:</th>"
				echo "<th>Data e hora:</th>"
				echo "</tr>"
				for x in $(cat /usr/lib/cgi-bin/log/user.txt) ; do
					echo "<tr>"
					for y in $(echo $x) ; do
						NAME=$(echo $y | cut -d";" -f1)
						ACT=$(echo $y | cut -d";" -f2)
						DATE=$(echo $y | cut -d";" -f3)
						echo "<td>$NAME</td>"
						echo "<td>$EMAIL</td>"
						echo "<td>$ACT</td>"
						echo "<td>$DATE</td>"
					done
					echo "</tr>"
				done
				echo "</table>"
				echo "</div>"
				echo "</body>"
				echo "</html>"
			elif [[ $REDIRECT == "/usr/lib/cgi-bin/log/login.cgi" ]] ; then 
				echo "<!DOCTYPE html>"
				echo "<html>"
				echo "<head>"
				echo "<link rel='stylesheet' type='text/css' href='../css/index.css'>" 
				echo "<script>"
				echo "function toggleSidebar(){"
				echo "document.getElementById(\"sidebar\").classList.toggle('active');"
				echo "}"
				echo "</script>"
				echo "</head>"
				echo "<body>"
				echo "<div id=\"sidebar\">"
				echo "<div class=\"toggle-btn\" onclick=\"toggleSidebar()\">"
				echo "<span class=\"span\"></span>"
				echo "<span class=\"span\"></span>"
				echo "<span class=\"span\"></span>"
				echo "</div>"
				cat "$MENUA"
				echo "</div>"
				echo "<div id=\"table-menu\">"
				echo "<table>"
				echo "<tr>"
				echo "<th>Nome de usuário:</th>"
				echo "<th>Ação:</th>"
				echo "<th>Data e hora:</th>"
				echo "</tr>"
				for x in $(cat /usr/lib/cgi-bin/log/login.txt) ; do
					echo "<tr>"
					for y in $(echo $x) ; do
						NAME=$(echo $y | cut -d";" -f1)
						ACT=$(echo $y | cut -d";" -f2)
						DATE=$(echo $y | cut -d";" -f3)
						echo "<td>$NAME</td>"
						echo "<td>$ACT</td>"
						echo "<td>$DATE</td>"
					done
					echo "</tr>"
				done
				echo "</table>"
				echo "</div>"
				echo "</body>"
				echo "</html>"
			elif [[ $REDIRECT == "/var/www/html/pages/aequip.html" ]] ; then
				echo "<!DOCTYPE html>"
				echo "<html>"
				echo "<head>"
				echo "<link rel='stylesheet' type='text/css' href='../css/index.css'>" 
				echo "<script>"
				echo "function toggleSidebar(){"
				echo "document.getElementById(\"sidebar\").classList.toggle('active');"
				echo "}"
				echo "</script>"
				echo "</head>"
				echo "<body>"
				echo "<div id=\"sidebar\">"
				echo "<div class=\"toggle-btn\" onclick=\"toggleSidebar()\">"
				echo "<span class=\"span\"></span>"
				echo "<span class=\"span\"></span>"
				echo "<span class=\"span\"></span>"
				echo "</div>"
				cat "$MENUA"
				echo "</div>"
				cat $REDIRECT
			elif [[ $REDIRECT == "/var/www/html/pages/requip.html" ]] ; then
				echo "<!DOCTYPE html>"
				echo "<html>"
				echo "<head>"
				echo "<link rel='stylesheet' type='text/css' href='../css/index.css'>" 
				echo "<script>"
				echo "function toggleSidebar(){"
				echo "document.getElementById(\"sidebar\").classList.toggle('active');"
				echo "}"
				echo "</script>"
				echo "</head>"
				echo "<body>"
				echo "<div id=\"sidebar\">"
				echo "<div class=\"toggle-btn\" onclick=\"toggleSidebar()\">"
				echo "<span class=\"span\"></span>"
				echo "<span class=\"span\"></span>"
				echo "<span class=\"span\"></span>"
				echo "</div>"
				cat "$MENUA"
				echo "</div>"
				cat $REDIRECT
			elif [[ $REDIRECT == "/var/www/html/pages/cequip.html" ]] ; then
				echo "<!DOCTYPE html>"
				echo "<html>"
				echo "<head>"
				echo "<link rel='stylesheet' type='text/css' href='../css/index.css'>" 
				echo "<script>"
				echo "function toggleSidebar(){"
				echo "document.getElementById(\"sidebar\").classList.toggle('active');"
				echo "}"
				echo "</script>"
				echo "</head>"
				echo "<body>"
				echo "<div id=\"sidebar\">"
				echo "<div class=\"toggle-btn\" onclick=\"toggleSidebar()\">"
				echo "<span class=\"span\"></span>"
				echo "<span class=\"span\"></span>"
				echo "<span class=\"span\"></span>"
				echo "</div>"
				cat "$MENUA"
				echo "</div>"
				cat $REDIRECT
			elif [[ $REDIRECT == "/var/www/html/pages/auser.html" ]] ; then
				echo "<!DOCTYPE html>"
				echo "<html>"
				echo "<head>"
				echo "<link rel='stylesheet' type='text/css' href='../css/index.css'>" 
				echo "<script>"
				echo "function toggleSidebar(){"
				echo "document.getElementById(\"sidebar\").classList.toggle('active');"
				echo "}"
				echo "</script>"
				echo "</head>"
				echo "<body>"
				echo "<div id=\"sidebar\">"
				echo "<div class=\"toggle-btn\" onclick=\"toggleSidebar()\">"
				echo "<span class=\"span\"></span>"
				echo "<span class=\"span\"></span>"
				echo "<span class=\"span\"></span>"
				echo "</div>"
				cat "$MENUA"
				echo "</div>"
				cat $REDIRECT
			elif [[ $REDIRECT == "/var/www/html/pages/ruser.html" ]] ; then
				echo "<!DOCTYPE html>"
				echo "<html>"
				echo "<head>"
				echo "<link rel='stylesheet' type='text/css' href='../css/index.css'>" 
				echo "<script>"
				echo "function toggleSidebar(){"
				echo "document.getElementById(\"sidebar\").classList.toggle('active');"
				echo "}"
				echo "</script>"
				echo "</head>"
				echo "<body>"
				echo "<div id=\"sidebar\">"
				echo "<div class=\"toggle-btn\" onclick=\"toggleSidebar()\">"
				echo "<span class=\"span\"></span>"
				echo "<span class=\"span\"></span>"
				echo "<span class=\"span\"></span>"
				echo "</div>"
				cat "$MENUA"
				echo "</div>"
				cat $REDIRECT
			elif [[ $REDIRECT == "/var/www/html/pages/cuser.html" ]] ; then
				echo "<!DOCTYPE html>"
				echo "<html>"
				echo "<head>"
				echo "<link rel='stylesheet' type='text/css' href='../css/index.css'>" 
				echo "<script>"
				echo "function toggleSidebar(){"
				echo "document.getElementById(\"sidebar\").classList.toggle('active');"
				echo "}"
				echo "</script>"
				echo "</head>"
				echo "<body>"
				echo "<div id=\"sidebar\">"
				echo "<div class=\"toggle-btn\" onclick=\"toggleSidebar()\">"
				echo "<span class=\"span\"></span>"
				echo "<span class=\"span\"></span>"
				echo "<span class=\"span\"></span>"
				echo "</div>"
				cat "$MENUA"
				echo "</div>"
				cat $REDIRECT
			elif [[ $REDIRECT == "/var/www/html/pages/doc.html" ]] ; then
				echo "<!DOCTYPE html>"
				echo "<html>"
				echo "<head>"
				echo "<link rel='stylesheet' type='text/css' href='../css/index.css'>" 
				echo "<script>"
				echo "function toggleSidebar(){"
				echo "document.getElementById(\"sidebar\").classList.toggle('active');"
				echo "}"
				echo "</script>"
				echo "</head>"
				echo "<body>"
				echo "<div id=\"sidebar\">"
				echo "<div class=\"toggle-btn\" onclick=\"toggleSidebar()\">"
				echo "<span class=\"span\"></span>"
				echo "<span class=\"span\"></span>"
				echo "<span class=\"span\"></span>"
				echo "</div>"
				cat "$MENUA"
				echo "</div>"
				cat $REDIRECT
			elif [[ $REDIRECT == "/var/www/html/pages/aus.html" ]] ; then
				echo "<!DOCTYPE html>"
				echo "<html>"
				echo "<head>"
				echo "<link rel='stylesheet' type='text/css' href='../css/index.css'>" 
				echo "<script>"
				echo "function toggleSidebar(){"
				echo "document.getElementById(\"sidebar\").classList.toggle('active');"
				echo "}"
				echo "</script>"
				echo "</head>"
				echo "<body>"
				echo "<div id=\"sidebar\">"
				echo "<div class=\"toggle-btn\" onclick=\"toggleSidebar()\">"
				echo "<span class=\"span\"></span>"
				echo "<span class=\"span\"></span>"
				echo "<span class=\"span\"></span>"
				echo "</div>"
				cat "$MENUA"
				echo "</div>"
				cat $REDIRECT
			elif [[ $REDIRECT == "/var/www/html/pages/sup.html" ]] ; then
				echo "<!DOCTYPE html>"
				echo "<html>"
				echo "<head>"
				echo "<link rel='stylesheet' type='text/css' href='../css/index.css'>" 
				echo "<script>"
				echo "function toggleSidebar(){"
				echo "document.getElementById(\"sidebar\").classList.toggle('active');"
				echo "}"
				echo "</script>"
				echo "</head>"
				echo "<body>"
				echo "<div id=\"sidebar\">"
				echo "<div class=\"toggle-btn\" onclick=\"toggleSidebar()\">"
				echo "<span class=\"span\"></span>"
				echo "<span class=\"span\"></span>"
				echo "<span class=\"span\"></span>"
				echo "</div>"
				cat "$MENUA"
				echo "</div>"
				cat $REDIRECT
			elif [[ $REDIRECT == "Chamado" ]] ; then
				echo "<!DOCTYPE html>"
				echo "<html>"
				echo "<head>"
				echo "<link rel='stylesheet' type='text/css' href='../css/index.css'>" 
				echo "<script>"
				echo "function toggleSidebar(){"
				echo "document.getElementById(\"sidebar\").classList.toggle('active');"
				echo "}"
				echo "</script>"
				echo "</head>"
				echo "<body>"
				echo "<div id=\"sidebar\">"
				echo "<div class=\"toggle-btn\" onclick=\"toggleSidebar()\">"
				echo "<span class=\"span\"></span>"
				echo "<span class=\"span\"></span>"
				echo "<span class=\"span\"></span>"
				echo "</div>"
				cat "$MENUA"
				echo "</div>"
				cat "/var/www/html/pages/called.html"
			elif [[ $REDIRECT == "Atualizar" ]] ; then
				echo "<script>"
				echo "location.href='../index.html'"
				echo "</script>"
			elif [[ $REDIRECT == "Detalhes" ]] ; then
				echo "<!DOCTYPE html>"
				echo "<html>"
				echo "<head>"
				echo "<link rel='stylesheet' type='text/css' href='../css/index.css'>" 
				echo "<script>"
				echo "function toggleSidebar(){"
				echo "document.getElementById(\"sidebar\").classList.toggle('active');"
				echo "}"
				echo "</script>"
				echo "</head>"
				echo "<body>"
				echo "<div id=\"sidebar\">"
				echo "<div class=\"toggle-btn\" onclick=\"toggleSidebar()\">"
				echo "<span class=\"span\"></span>"
				echo "<span class=\"span\"></span>"
				echo "<span class=\"span\"></span>"
				echo "</div>"
				cat "$MENUA"
				echo "</div>"
				echo "<div id=\"table-menu\">"
				echo "<table>"
				echo "<tr>"
				echo "<th>Data e hora:</th>"
				echo "<th>Nome:</th>"
				echo "<th>Localização:</th>"
				echo "<th>Endereço de IP:</th>"
				echo "<th>Status:</th>"
				echo "</tr>"
				for x in $(cat /usr/lib/cgi-bin/log/rdetail.txt) ; do
					echo "<tr>"
					for y in $(echo $x) ; do
						DATE=$(echo $y | cut -d";" -f1)
						NAME=$(echo $y | cut -d";" -f2)
						LOCAL=$(echo $y | cut -d";" -f3)
						IP=$(echo $y | cut -d";" -f4)
						STATUS=$(echo $y | cut -d";" -f5)
						echo "<td>$DATE</td>"
						echo "<td>$NAME</td>"
						echo "<td>$LOCAL</td>"
						echo "<td>$IP</td>"
						echo "<td>$STATUS</td>"
					done
					echo "</tr>"
				done
				echo "</table>"
				echo "</div>"
				echo "</body>"
				echo "</html>"
			else
				echo "<!DOCTYPE html>"
				echo "<html>"
				echo "<head>"
				echo "<link rel='stylesheet' type='text/css' href='../css/index.css'>" 
				echo "<script>"
				echo "function toggleSidebar(){"
				echo "document.getElementById(\"sidebar\").classList.toggle('active');"
				echo "}"
				echo "</script>"
				echo "</head>"
				echo "<body>"
				echo "<div id=\"sidebar\">"
				echo "<div class=\"toggle-btn\" onclick=\"toggleSidebar()\">"
				echo "<span class=\"span\"></span>"
				echo "<span class=\"span\"></span>"
				echo "<span class=\"span\"></span>"
				echo "</div>"
				cat "$MENUA"
				echo "</div>"
				echo "<div id=\"table-menu\">"
				echo "<form method='POST'>"
 				echo "<input type='submit' name='var' value='Iniciar' formaction='serv.cgi'>"
				echo "<input type='submit' name='var' value='Encerrar' formaction='serv.cgi'>"
				echo "<input type='submit' name='var' value='Reiniciar' formaction='serv.cgi'>"
				echo "<input type='submit' name='var' value='Status' formaction='serv.cgi'>"
				echo "<input type='submit' name='var' value='Atualizar' formaction='index.cgi'>"
				echo "<input type='submit' name='var' value='Detalhes' formaction='index.cgi'>"
				echo "<input type='submit' name='var' value='Chamado' formaction='index.cgi'><br><br>"
				echo "<table>"
				echo "<tr>"
				echo "<th>Nome:</th>"
				echo "<th>Localização:</th>"
				echo "<th>Endereço de IP:</th>"
				echo "<th>Status:</th>"
				echo "</tr>"
				for x in $(cat /usr/lib/cgi-bin/log/rsimple.txt) ; do
					echo "<tr>"
					for y in $(echo $x) ; do
						NAME=$(echo $y | cut -d";" -f1)
						LOCAL=$(echo $y | cut -d";" -f2)
						IP=$(echo $y | cut -d";" -f3)
						STATUS=$(echo $y | cut -d";" -f4)
						echo "<td>$NAME</td>"
						echo "<td>$LOCAL</td>"
						echo "<td>$IP</td>"
						echo "<td>$STATUS</td>"
					done
					echo "</tr>"
				done
				echo "</table>"
				echo "</form>"
				echo "</div>"
				echo "</body>"
				echo "</html>"
			fi
			elif [[ $TYPE == "common" ]] ; then
				if [[ $REDIRECT == "/usr/lib/cgi-bin/vequip.cgi" ]] ; then
					echo "<!DOCTYPE html>"
					echo "<html>"
					echo "<head>"
					echo "<link rel='stylesheet' type='text/css' href='../css/index.css'>" 
					echo "<script>"
					echo "function toggleSidebar(){"
					echo "document.getElementById("sidebar").classList.toggle('active');"
					echo "}"
					echo "</script>"
					echo "</head>"
					echo "<body>"
					echo "<div id=\"sidebar\">"
					echo "<div class=\"toggle-btn\" onclick=\"toggleSidebar()\">"
					echo "<span></span>"
					echo "<span></span>"
					echo "<span></span>"
					echo "</div>"
					cat "$MENUC"
					echo "</div>"
					echo "<div id=\"table-menu\">"
					echo "<table>"
					echo "<tr>"
					echo "<th>Nome:</th>"
					echo "<th>Localização:</th>"
					echo "<th>Endereço de IP:</th>"
					echo "</tr>"
					for x in $(cat equips.csv) ; do
						echo "<tr>"
						for y in $(echo $x) ; do
							NAME=$(echo $y | cut -d";" -f1)
							LOCAL=$(echo $y | cut -d";" -f2)
							IP=$(echo $y | cut -d";" -f3)
							echo "<td>$NAME</td>"
							echo "<td>$LOCAL</td>"
							echo "<td>$IP</td>"
						done
					echo "</tr>"
					done
					echo "</table>"
					echo "</div>"
					echo "</body>"
					echo "</html>"
				elif [[ $REDIRECT == "Detalhes" ]] ; then
					echo "<!DOCTYPE html>"
					echo "<html>"
					echo "<head>"
					echo "<link rel='stylesheet' type='text/css' href='../css/index.css'>" 
					echo "<script>"
					echo "function toggleSidebar(){"
					echo "document.getElementById("sidebar").classList.toggle('active');"
					echo "}"
					echo "</script>"
					echo "</head>"
					echo "<body>"
					echo "<div id=\"sidebar\">"
					echo "<div class=\"toggle-btn\" onclick=\"toggleSidebar()\">"
					echo "<span></span>"
					echo "<span></span>"
					echo "<span></span>"
					echo "</div>"
					cat "$MENUC"
					echo "</div>"
					echo "<div id=\"table-menu\">"
					echo "<table>"
					echo "<tr>"
					echo "<th>Data e hora:</th>"
					echo "<th>Nome:</th>"
					echo "<th>Localização:</th>"
					echo "<th>Endereço de IP:</th>"
					echo "<th>Status:</th>"
					echo "</tr>"
					for x in $(cat /usr/lib/cgi-bin/log/rdetail.txt) ; do
						echo "<tr>"
						for y in $(echo $x) ; do
							DATE=$(echo $y | cut -d";" -f1)
							NAME=$(echo $y | cut -d";" -f2)
							LOCAL=$(echo $y | cut -d";" -f3)
							IP=$(echo $y | cut -d";" -f4)
							STATUS=$(echo $y | cut -d";" -f5)
							echo "<td>$DATE</td>"
							echo "<td>$NAME</td>"
							echo "<td>$LOCAL</td>"
							echo "<td>$IP</td>"
							echo "<td>$STATUS</td>"
						done
						echo "</tr>"
					done
					echo "</table>"
					echo "</div>"
					echo "</body>"
					echo "</html>"
				elif [[ $REDIRECT == "Chamado" ]] ; then
					echo "<!DOCTYPE html>"
					echo "<html>"
					echo "<head>"
					echo "<link rel='stylesheet' type='text/css' href='../css/index.css'>" 
					echo "<script>"
					echo "function toggleSidebar(){"
					echo "document.getElementById("sidebar").classList.toggle('active');"
					echo "}"
					echo "</script>"
					echo "</head>"
					echo "<body>"
					echo "<div id=\"sidebar\">"
					echo "<div class=\"toggle-btn\" onclick=\"toggleSidebar()\">"
					echo "<span></span>"
					echo "<span></span>"
					echo "<span></span>"
					echo "</div>"
					cat "$MENUC"
					echo "</div>"
					cat "/var/www/html/pages/called.html"
				elif [[ $REDIRECT == "Atualizar" ]] ; then
					echo "<script>"
					echo "location.href='../index.html'"
					echo "</script>"
				else
					echo "<!DOCTYPE html>"
					echo "<html>"
					echo "<head>"
					echo "<link rel='stylesheet' type='text/css' href='../css/index.css'>" 
					echo "<script>"
					echo "function toggleSidebar(){"
					echo "document.getElementById("sidebar").classList.toggle('active');"
					echo "}"
					echo "</script>"
					echo "</head>"
					echo "<body>"
					echo "<div id=\"sidebar\">"
					echo "<div class=\"toggle-btn\" onclick=\"toggleSidebar()\">"
					echo "<span></span>"
					echo "<span></span>"
					echo "<span></span>"
					echo "</div>"
					cat "$MENUC"
					echo "</div>"
					echo "<div id=\"table-menu\">"
					echo "<form method='POST'>"
					echo "<input type='submit' name='var' value='Iniciar' formaction='serv.cgi'>"
					echo "<input type='submit' name='var' value='Encerrar' formaction='serv.cgi'>"
					echo "<input type='submit' name='var' value='Reiniciar' formaction='serv.cgi'>"
					echo "<input type='submit' name='var' value='Status' formaction='serv.cgi'>"
					echo "<input type='submit' name='var' value='Atualizar' formaction='index.cgi'>"
					echo "<input type='submit' name='var' value='Detalhes' formaction='index.cgi'>"
					echo "<input type='submit' name='var' value='Chamado' formaction='index.cgi'><br><br>"
					echo "<table>"
					echo "<tr>"
					echo "<th>Nome:</th>"
					echo "<th>Localização:</th>"
					echo "<th>Endereço de IP:</th>"
					echo "<th>Status:</th>"
					echo "</tr>"
					for x in $(cat /usr/lib/cgi-bin/log/rsimple.txt) ; do
						echo "<tr>"
						for y in $(echo $x) ; do
							NAME=$(echo $y | cut -d";" -f1)
							LOCAL=$(echo $y | cut -d";" -f2)
							IP=$(echo $y | cut -d";" -f3)
							STATUS=$(echo $y | cut -d";" -f4)
							echo "<td>$NAME</td>"
							echo "<td>$LOCAL</td>"
							echo "<td>$IP</td>"
							echo "<td>$STATUS</td>"
						done
						echo "</tr>"
					done
					echo "</table>"
					echo "</form>"
					echo "</div>"
					echo "</body>"
					echo "</html>"
				fi
			else
				cat $LOGIN
			fi
		else
			cat $LOGIN
		fi
	else
		cat $LOGIN
	fi
